#!/sbin/busybox sh

if [ -f $2 ];then
	FILEVAR=digital_abs_$(basename $2)

	if [ -z $3 ]; then
		evalcmd='eval echo \$$FILEVAR'
		if [ "a`eval $evalcmd`" == "a" ]; then
			val=`cat $2`
			val=`expr $val - 128`
			val=`expr $val / 2`
			eval $FILEVAR=$val
			echo $FILEVAR=$val >> $DEFAULT_PROFILE
		fi
	else
		echo `expr 128 + $3 \* 2` > $2
		eval $FILEVAR=$3
	fi

	eval echo \$$FILEVAR
fi
