#!/sbin/busybox sh

if [ -z $2 ];then
	if [ -z $vnswap_size ]; then
		vnswap_size=`cat /sys/devices/virtual/block/vnswap0/disksize`
		vnswap_size=`expr $vnswap_size \/ 1024 \/ 1024`
		echo vnswap_size=$vnswap_size >> $DEFAULT_PROFILE
	fi
else
	vnswap_size=$2

	swapoff /dev/block/vnswap0 > /dev/null 2>&1

	if [ $vnswap_size -gt 0 ]; then
		echo `expr $vnswap_size \* 1024 \* 1024` > /sys/devices/virtual/block/vnswap0/disksize
		mkswap /dev/block/vnswap0 > /dev/null 2>&1
		swapon /dev/block/vnswap0 > /dev/null 2>&1
	fi
fi

echo $vnswap_size
