#!/sbin/busybox sh

BB=/sbin/busybox

$BB date >>boot.txt
exec >>boot.txt 2>&1

$BB echo "generating mount directories..."
$BB mkdir proc
$BB mkdir sys
$BB mkdir system

$BB mkdir /dev
$BB mkdir /dev/block

$BB mkdir /mnt
$BB chmod 755 /mnt

$BB echo "generating device nodes..."
$BB mknod /dev/block/mmcblk0 b 179 0
$BB mknod /dev/block/mmcblk0p2 b 179 9
$BB mknod /dev/block/mmcblk0p6 b 179 12
$BB mknod /dev/block/loop0 b 7 0

$BB echo "mounting devices..."
$BB mount -t proc proc /proc
$BB mount -t sysfs sysfs /sys

export _PATH="$PATH"
export PATH=/sbin

cd /
$BB rm /init

$BB mv -f /init-orig /init

export PATH="${_PATH}"
exec /init
